version: '2.1'
orbs:
  slack: circleci/slack@4.1.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.16.0

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - slack/notify:
          event: fail
          template: SLACK_FAIL_TEST_TEMPLATE

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.16.0

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run release
      - slack/notify:
          event: fail
          template: SLACK_FAIL_TEMPLATE
      - slack/notify:
          event: pass
          template: SLACK_PASS_TEMPLATE

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context:
            - slack-secrets
      - deploy:
          context:
            - slack-secrets
          filters:
            branches:
              only:
                - master
                - /^gh-.*/
          requires:
            - test
